import { useCallback, useEffect, useState } from "react";
import { BrowserRouter, Link, Route, Routes, useNavigate } from "react-router-dom";
import { ArrowLeft, ArrowUpRight, Check, Film, Image as ImageIcon, Loader2, LockKeyhole, LogOut, Pencil, Plus, Trash2, X } from "lucide-react";
import axios from "axios";
import "@/App.css";
import "@/logo-overrides.css";
import "@/theme.css";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
const client = axios.create({ baseURL: API, withCredentials: true });
const contact = { phone: "+91 9521174243", email: "signaturestudio02@gmail.com" };
const LOGO_ASSET = "https://customer-assets-cm19k8pv.emergentagent.net/job_studio-portfolio-65/artifacts/e2n22xze_IMG_8064.PNG";
const categoryImages = {
  "Restaurant / Café": "https://images.unsplash.com/photo-1702450900245-a86084f9e31d?auto=format&fit=crop&w=900&q=85",
  "Gym / Fitness": "https://images.unsplash.com/photo-1576289412237-698ae5427f27?auto=format&fit=crop&w=900&q=85",
  Healthcare: "https://images.pexels.com/photos/32721706/pexels-photo-32721706.jpeg?auto=compress&cs=tinysrgb&w=900",
  "Fashion / Retail": "https://images.unsplash.com/photo-1652561751125-91629417d6ae?auto=format&fit=crop&w=900&q=85",
  "Hotel & Resort": "https://images.pexels.com/photos/12770192/pexels-photo-12770192.jpeg?auto=compress&cs=tinysrgb&w=900",
  "Creator / Brand": "https://images.pexels.com/photos/32721706/pexels-photo-32721706.jpeg?auto=compress&cs=tinysrgb&w=900",
};

function errorText(error) { const detail = error?.response?.data?.detail; if (Array.isArray(detail)) return detail.map((item) => item.msg || "Invalid input").join(" "); return detail || error?.message || "Something went wrong."; }
function Logo({ testId = "brand-logo" }) { return <Link to="/" className="brand" data-testid={testId}><img src={LOGO_ASSET} alt="SIGNATURE STUDIO" /><span>SIGNATURE STUDIO</span></Link>; }
function Header({ admin = false }) { return <header className="site-header"><Logo testId="header-brand-logo" /><div className="header-right"><div className="header-contact"><a href={`tel:${contact.phone}`} data-testid="header-phone">{contact.phone}</a><a href={`mailto:${contact.email}`} data-testid="header-email">{contact.email}</a></div>{admin ? <Link to="/admin" className="owner-link" data-testid="admin-dashboard-link">STUDIO DESK <ArrowUpRight size={13} /></Link> : <Link to="/login" className="owner-link" data-testid="owner-login-link"><LockKeyhole size={13} /> OWNER ACCESS</Link>}</div></header>; }
function Footer() { return <footer className="site-footer"><Logo testId="footer-brand-logo" /><span data-testid="footer-slogan">we create your signature edits &amp; design</span><a href={`mailto:${contact.email}`} data-testid="footer-email">{contact.email}</a></footer>; }

function Home() {
  const [categories, setCategories] = useState([]); const [selected, setSelected] = useState(""); const [tab, setTab] = useState("reel"); const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { client.get("/portfolio/categories").then((response) => setCategories(response.data.categories)).catch((err) => setError(errorText(err))).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (!selected) return; setLoading(true); client.get("/portfolio", { params: { category: selected, media_type: tab } }).then((response) => setItems(response.data.items)).catch((err) => setError(errorText(err))).finally(() => setLoading(false)); }, [selected, tab]);
  const selectCategory = (category) => { setSelected(category); setTab("reel"); window.scrollTo({ top: 0, behavior: "smooth" }); };
  return <div className="dark-shell"><Header /><main className="home-main">{selected ? <WorkView category={selected} tab={tab} setTab={setTab} items={items} loading={loading} onBack={() => setSelected("")} /> : <><section className="hero"><p className="micro-label">CREATIVE CONTENT STUDIO</p><h1>WE CREATE<br />YOUR<br /><span>SIGNATURE</span><br />EDITS &amp; DESIGN</h1><p className="hero-note">Choose your niche to view Reels and Designs</p></section><section className="category-section"><div className="section-label"><span>SELECT YOUR NICHE</span><span>{categories.length || "06"} CATEGORIES</span></div>{error && <p className="error-message" data-testid="portfolio-error">{error}</p>}{loading && !categories.length ? <div className="loading-state" data-testid="categories-loading"><Loader2 className="spin" /> LOADING CATEGORIES</div> : <div className="category-grid" data-testid="category-list">{categories.map((category, index) => <button key={category} className="category-card" onClick={() => selectCategory(category)} data-testid={`category-${category.toLowerCase().replaceAll(" ", "-").replaceAll("/", "")}`}><img src={categoryImages[category] || categoryImages["Creator / Brand"]} alt="" /><span className="card-shade" /><span className="category-index">{String(index + 1).padStart(2, "0")}</span><strong>{category}</strong><ArrowUpRight size={15} /></button>)}</div>}</section></>}</main><Footer /></div>;
}
function WorkView({ category, tab, setTab, items, loading, onBack }) { return <section className="work-view" data-testid="portfolio-section"><div className="work-toolbar"><button onClick={onBack} className="back-control" data-testid="portfolio-back-button"><ArrowLeft size={15} /> ALL NICHES</button><span>{category.toUpperCase()}</span><div className="work-tabs"><button className={tab === "reel" ? "active" : ""} onClick={() => setTab("reel")} data-testid="reels-tab"><Film size={13} /> REELS</button><button className={tab === "design" ? "active" : ""} onClick={() => setTab("design")} data-testid="designs-tab"><ImageIcon size={13} /> DESIGNS</button></div></div><div className="work-heading"><p className="micro-label">{category.toUpperCase()} / SELECTED WORK</p><h1>{tab === "reel" ? "REELS" : "DESIGNS"}</h1></div>{loading ? <div className="loading-state" data-testid="portfolio-loading"><Loader2 className="spin" /> LOADING WORK</div> : items.length ? <div className="media-grid" data-testid="portfolio-grid">{items.map((item) => <MediaCard item={item} key={item.id} />)}</div> : <div className="empty-state" data-testid="portfolio-empty"><span>+</span><p>NO {tab === "reel" ? "REELS" : "DESIGNS"} IN THIS CATEGORY YET</p></div>}</section>; }
function MediaCard({ item }) { const source = item.media_data || item.media_url; return <article className="media-card" data-testid={`portfolio-item-${item.id}`}>{item.media_type === "reel" ? <video src={source} controls playsInline preload="metadata" data-testid={`portfolio-video-${item.id}`} /> : <img src={source} alt={item.title || item.category} data-testid={`portfolio-image-${item.id}`} />}<div className="media-meta"><div><span>{item.label || item.category}</span><h3>{item.title || "UNTITLED STUDY"}</h3></div><ArrowUpRight size={14} /></div></article>; }

function Login() { const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const nav = useNavigate(); const submit = async (event) => { event.preventDefault(); setError(""); try { await client.post("/auth/login", { email, password }); nav("/admin"); } catch (err) { setError(errorText(err)); } }; return <AuthFrame><form className="auth-form" onSubmit={submit} data-testid="login-form"><p className="micro-label">OWNER ACCESS / RETURNING OWNER</p><h1>WELCOME<br /><span>BACK.</span></h1><label>EMAIL<input value={email} onChange={(event) => setEmail(event.target.value)} type="email" required data-testid="login-email-input" /></label><label>PASSWORD<input value={password} onChange={(event) => setPassword(event.target.value)} type="password" required data-testid="login-password-input" /></label>{error && <p className="error-message" data-testid="login-error">{error}</p>}<button className="primary-button" type="submit" data-testid="login-submit-button">LOGIN <ArrowUpRight size={14} /></button><Link className="auth-secondary" to="/setup" data-testid="create-owner-account-link">CREATE OWNER ACCOUNT</Link><Link className="auth-secondary" to="/" data-testid="login-back-link">RETURN TO SITE</Link></form></AuthFrame>; }
function Setup() { const [form, setForm] = useState({ name: "", email: "", password: "", confirm: "" }); const [error, setError] = useState(""); const nav = useNavigate(); const submit = async (event) => { event.preventDefault(); if (form.password !== form.confirm) return setError("Passwords do not match."); try { await client.post("/auth/register", { name: form.name, email: form.email, password: form.password }); nav("/admin"); } catch (err) { setError(errorText(err)); } }; return <AuthFrame><form className="auth-form" onSubmit={submit} data-testid="setup-form"><p className="micro-label">OWNER ACCESS / FIRST SETUP</p><h1>CREATE<br /><span>ACCOUNT.</span></h1><p className="auth-description">Create the private studio account once. After setup, use login whenever you need to update work.</p><label>NAME<input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required data-testid="setup-name-input" /></label><label>EMAIL<input value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} type="email" required data-testid="setup-email-input" /></label><label>PASSWORD<input value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} type="password" minLength="8" required data-testid="setup-password-input" /></label><label>CONFIRM PASSWORD<input value={form.confirm} onChange={(event) => setForm({ ...form, confirm: event.target.value })} type="password" minLength="8" required data-testid="setup-confirm-input" /></label>{error && <p className="error-message" data-testid="setup-error">{error}</p>}<button className="primary-button" type="submit" data-testid="setup-submit-button">CREATE ACCOUNT <ArrowUpRight size={14} /></button><Link className="auth-secondary" to="/login" data-testid="setup-login-link">I ALREADY HAVE AN ACCOUNT</Link></form></AuthFrame>; }
function AuthFrame({ children }) { return <div className="dark-shell auth-shell"><Header /><main className="auth-main"><div className="auth-intro"><p className="micro-label">SIGNATURE STUDIO / PRIVATE AREA</p><p>Portfolio Manager<br />For Studio Owner</p></div>{children}</main></div>; }

function Admin() { const [user, setUser] = useState(null); const [items, setItems] = useState([]); const [editing, setEditing] = useState(null); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const nav = useNavigate(); const load = useCallback(async () => { try { const response = await client.get("/admin/portfolio"); setItems(response.data.items); } catch (err) { setError(errorText(err)); } }, []); useEffect(() => { let active = true; (async () => { try { const auth = await client.get("/auth/me"); if (!active) return; setUser(auth.data); await load(); } catch { if (active) nav("/login"); } finally { if (active) setLoading(false); } })(); return () => { active = false; }; }, [load, nav]); const logout = async () => { await client.post("/auth/logout"); nav("/"); }; if (loading) return <div className="dark-shell loading-state full" data-testid="admin-loading"><Loader2 className="spin" /> OPENING STUDIO DESK</div>; if (!user) return null; return <div className="dark-shell"><Header admin /><main className="admin-main"><div className="admin-title"><div><p className="micro-label">PRIVATE STUDIO DESK / {user.email}</p><h1>PORTFOLIO<br /><span>MANAGER</span></h1></div><button onClick={() => setEditing({})} className="primary-button" data-testid="add-portfolio-button"><Plus size={15} /> ADD WORK</button></div>{error && <p className="error-message" data-testid="admin-error">{error}</p>}{notice && <p className="success-message" data-testid="admin-success"><Check size={14} /> {notice}</p>}<div className="admin-list" data-testid="admin-portfolio-list">{items.length ? items.map((item) => <div className="admin-row" key={item.id} data-testid={`admin-item-${item.id}`}><div className="admin-thumb">{item.media_type === "reel" ? <Film size={19} /> : <img src={item.media_data || item.media_url} alt="" />}</div><div><span data-testid={`admin-item-label-${item.id}`}>{item.category} / {item.media_type}</span><h3>{item.title || "UNTITLED STUDY"}</h3></div><div className="row-actions"><button onClick={() => setEditing(item)} title="Edit" data-testid={`edit-item-${item.id}`}><Pencil size={15} /></button><button onClick={async () => { if (window.confirm("Delete this work?")) { await client.delete(`/admin/portfolio/${item.id}`); await load(); setNotice("WORK REMOVED"); } }} title="Delete" data-testid={`delete-item-${item.id}`}><Trash2 size={15} /></button></div></div>) : <div className="empty-state"><span>+</span><p>YOUR WORK LIBRARY IS READY FOR ITS FIRST PIECE.</p></div>}</div></main><footer className="admin-footer"><span data-testid="signed-in-user">SIGNED IN AS {user.email}</span><button onClick={logout} data-testid="logout-button"><LogOut size={14} /> SIGN OUT</button></footer>{editing !== null && <PortfolioForm item={editing} close={() => setEditing(null)} saved={() => { setEditing(null); load(); setNotice("WORK SAVED TO LIVE PORTFOLIO"); }} />}</div>; }
function PortfolioForm({ item, close, saved }) { const [form, setForm] = useState({ category: item.category || "Restaurant / Café", media_type: item.media_type || "reel", title: item.title || "", label: item.label || "", media_url: item.media_url || "", media_data: item.media_data || "", mime_type: item.mime_type || "" }); const [error, setError] = useState(""); const update = (event) => setForm({ ...form, [event.target.name]: event.target.value }); const file = (event) => { const selected = event.target.files[0]; if (!selected) return; if (selected.size > 30 * 1024 * 1024) return setError("CHOOSE A FILE UNDER 30 MB."); const reader = new FileReader(); reader.onload = () => setForm((current) => ({ ...current, media_data: reader.result, media_url: "", mime_type: selected.type, media_type: selected.type.startsWith("video") ? "reel" : "design" })); reader.readAsDataURL(selected); }; const submit = async (event) => { event.preventDefault(); setError(""); try { if (!form.media_url && !form.media_data) throw new Error("ADD A FILE OR HOSTED MEDIA URL."); if (item.id) await client.put(`/admin/portfolio/${item.id}`, form); else await client.post("/admin/portfolio", form); saved(); } catch (err) { setError(errorText(err)); } }; return <div className="modal-backdrop"><form className="portfolio-form" onSubmit={submit} data-testid="portfolio-form"><button type="button" className="close-button" onClick={close} data-testid="close-portfolio-form"><X size={17} /></button><p className="micro-label">{item.id ? "EDIT WORK" : "ADD NEW WORK"}</p><h2>{item.id ? "REFINE THIS PIECE" : "ADD TO LIBRARY"}</h2><label>NICHE / CATEGORY<input name="category" value={form.category} onChange={update} required data-testid="portfolio-category-input" /></label><div className="form-split"><label>TYPE<select name="media_type" value={form.media_type} onChange={update} data-testid="portfolio-type-input"><option value="reel">REEL / VIDEO</option><option value="design">DESIGN / IMAGE</option></select></label><label>SHORT LABEL<input name="label" value={form.label} onChange={update} placeholder="CAMPAIGN 01" data-testid="portfolio-label-input" /></label></div><label>TITLE<input name="title" value={form.title} onChange={update} placeholder="OPTIONAL TITLE" data-testid="portfolio-title-input" /></label><label>UPLOAD FILE<input type="file" accept="image/*,video/*" onChange={file} data-testid="portfolio-file-input" /></label><div className="or-line">OR USE A HOSTED URL</div><label>MEDIA URL<input name="media_url" value={form.media_url} onChange={update} placeholder="HTTPS://..." data-testid="portfolio-url-input" /></label>{form.media_data && <p className="file-ready" data-testid="file-ready-indicator"><Check size={14} /> FILE READY</p>}{error && <p className="error-message" data-testid="portfolio-form-error">{error}</p>}<button className="primary-button" type="submit" data-testid="save-portfolio-button">SAVE TO LIVE PORTFOLIO <ArrowUpRight size={14} /></button></form></div>; }

export default function App() { return <BrowserRouter><Routes><Route path="/" element={<Home />} /><Route path="/login" element={<Login />} /><Route path="/setup" element={<Setup />} /><Route path="/admin" element={<Admin />} /></Routes></BrowserRouter>; }