import { useEffect, useState } from "react";
import { BrowserRouter, Link, Route, Routes, useNavigate } from "react-router-dom";
import { ArrowUpRight, Check, Film, Image as ImageIcon, Loader2, LockKeyhole, LogOut, Pencil, Plus, Trash2, X } from "lucide-react";
import axios from "axios";
import "@/App.css";
import "@/logo-overrides.css";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
const client = axios.create({ baseURL: API, withCredentials: true });
const contact = { phone: "+91 9521174243", email: "signaturestudio02@gmail.com" };
const LOGO_ASSET = "https://customer-assets-cm19k8pv.emergentagent.net/job_studio-portfolio-65/artifacts/e2n22xze_IMG_8064.PNG";

function Logo({ compact = false, testId = "brand-logo" }) { return <Link to="/" className={`logo ${compact ? "logo-compact" : ""}`} data-testid={testId}><img src={LOGO_ASSET} alt="SIGNATURE STUDIO logo" /></Link>; }
function Header({ admin = false }) { return <header className="site-header"><Logo testId="header-brand-logo" /><div className="header-contact"><a href={`tel:${contact.phone}`} data-testid="header-phone">{contact.phone}</a><a href={`mailto:${contact.email}`} data-testid="header-email">{contact.email}</a></div>{admin ? <Link to="/admin" className="admin-link" data-testid="admin-dashboard-link">Studio desk <ArrowUpRight size={15} /></Link> : <Link to="/login" className="admin-link" data-testid="owner-login-link"><LockKeyhole size={14} /> Owner login</Link>}</header>; }
function Footer() { return <footer className="site-footer"><Logo compact testId="footer-brand-logo" /><span data-testid="footer-slogan">we create your signature edits &amp; design</span><a href={`mailto:${contact.email}`} data-testid="footer-email">{contact.email}</a></footer>; }

function Home() {
  const [categories, setCategories] = useState([]); const [selected, setSelected] = useState(""); const [items, setItems] = useState([]); const [tab, setTab] = useState("reel"); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { client.get("/portfolio/categories").then(r => setCategories(r.data.categories)).catch(() => setError("We couldn't load the studio categories.")).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (!selected) return; setLoading(true); client.get("/portfolio", { params: { category: selected, media_type: tab } }).then(r => setItems(r.data.items)).catch(() => setError("We couldn't load this portfolio yet.")).finally(() => setLoading(false)); }, [selected, tab]);
  return <div className="app-shell"><Header /><main className="home-main"><section className="intro"><p className="kicker">SIGNATURE STUDIO / 2024—25</p><h1>We create your<br /><em>signature</em> edits<br />&amp; design.</h1><p className="intro-note">Select a world to explore<br />our latest work.</p></section><section className="category-area"><div className="section-rule"><span>01 / SELECT A NICHE</span><span>{categories.length} collections</span></div>{error && <p className="error-message" data-testid="portfolio-error">{error}</p>}{loading && !categories.length ? <div className="loading-state" data-testid="categories-loading"><Loader2 className="spin" /> loading collections</div> : <div className="category-grid" data-testid="category-list">{categories.map((category, i) => <button key={category} className={`category-button ${selected === category ? "active" : ""}`} onClick={() => setSelected(category)} data-testid={`category-${category.toLowerCase().replaceAll(" ", "-")}`}><span>{String(i + 1).padStart(2, "0")}</span><strong>{category}</strong><ArrowUpRight size={18} /></button>)}</div>}</section>{selected && <section className="portfolio-area" data-testid="portfolio-section"><div className="portfolio-heading"><div><p className="kicker">02 / {selected.toUpperCase()}</p><h2>Selected work</h2></div><div className="tabs" role="tablist"><button onClick={() => setTab("reel")} className={tab === "reel" ? "active" : ""} data-testid="reels-tab"><Film size={15} /> Reels</button><button onClick={() => setTab("design")} className={tab === "design" ? "active" : ""} data-testid="designs-tab"><ImageIcon size={15} /> Designs</button></div></div>{loading ? <div className="loading-state" data-testid="portfolio-loading"><Loader2 className="spin" /> loading work</div> : items.length ? <div className={`portfolio-grid ${tab === "reel" ? "reels-grid" : ""}`} data-testid="portfolio-grid">{items.map(item => <MediaCard item={item} key={item.id} />)}</div> : <div className="empty-state" data-testid="portfolio-empty"><span>—</span><p>No {tab === "reel" ? "reels" : "designs"} in this collection yet.</p></div>}</section>}</main><Footer /></div>;
}
function MediaCard({ item }) { const source = item.media_data || item.media_url; return <article className="media-card" data-testid={`portfolio-item-${item.id}`}>{item.media_type === "reel" ? <video src={source} controls playsInline preload="metadata" data-testid={`portfolio-video-${item.id}`} /> : <img src={source} alt={item.title || item.category} data-testid={`portfolio-image-${item.id}`} /> }<div className="media-meta"><div><span>{item.label || item.category}</span><h3>{item.title || "Untitled study"}</h3></div><ArrowUpRight size={17} /></div></article>; }

function Login() { const [email, setEmail] = useState("signaturestudio02@gmail.com"); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const nav = useNavigate(); const submit = async e => { e.preventDefault(); setError(""); try { await client.post("/auth/login", { email, password }); nav("/admin"); } catch (err) { setError(err.response?.data?.detail || "Unable to sign in"); } }; return <div className="admin-shell"><Header /><main className="auth-main"><div className="auth-copy"><p className="kicker">PRIVATE STUDIO DESK</p><h1>Welcome<br /><em>back.</em></h1><p>Manage the work clients come to see.</p></div><form className="auth-form" onSubmit={submit} data-testid="login-form"><LockKeyhole size={20} /><h2>Owner login</h2><label>Email<input value={email} onChange={e => setEmail(e.target.value)} type="email" required data-testid="login-email-input" /></label><label>Password<input value={password} onChange={e => setPassword(e.target.value)} type="password" required data-testid="login-password-input" /></label>{error && <p className="error-message" data-testid="login-error">{error}</p>}<button className="primary-button" type="submit" data-testid="login-submit-button">Enter studio <ArrowUpRight size={17} /></button><Link to="/" className="back-link" data-testid="login-back-link">Return to portfolio</Link></form></main></div>; }

function Admin() { const [user, setUser] = useState(null); const [items, setItems] = useState([]); const [editing, setEditing] = useState(null); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const nav = useNavigate(); const load = async () => { try { const response = await client.get("/admin/portfolio"); setItems(response.data.items); } catch { setError("The work library could not be loaded. Please refresh."); } }; useEffect(() => { let active = true; (async () => { try { const auth = await client.get("/auth/me"); if (!active) return; setUser(auth.data); await load(); } catch { if (active) nav("/login"); } finally { if (active) setLoading(false); } })(); return () => { active = false; }; }, []); const logout = async () => { await client.post("/auth/logout"); nav("/"); }; if (loading) return <div className="loading-state full" data-testid="admin-loading"><Loader2 className="spin" /> opening desk</div>; if (!user) return null; return <div className="admin-shell"><Header admin /><main className="admin-main"><div className="admin-title"><div><p className="kicker">PRIVATE STUDIO DESK / {user.email}</p><h1>Work library</h1></div><button onClick={() => setEditing({})} className="primary-button" data-testid="add-portfolio-button"><Plus size={17} /> Add work</button></div>{error && <p className="error-message" data-testid="admin-error">{error}</p>}{notice && <p className="success-message" data-testid="admin-success"><Check size={16} /> {notice}</p>}<div className="admin-list" data-testid="admin-portfolio-list">{items.length ? items.map(item => <div className="admin-row" key={item.id} data-testid={`admin-item-${item.id}`}><div className="admin-thumb">{item.media_type === "reel" ? <Film /> : <img src={item.media_data || item.media_url} alt="" />}</div><div><span data-testid={`admin-item-label-${item.id}`}>{item.category} / {item.media_type}</span><h3>{item.title || "Untitled study"}</h3></div><div className="row-actions"><button onClick={() => setEditing(item)} title="Edit" data-testid={`edit-item-${item.id}`}><Pencil size={16} /></button><button onClick={async () => { if (window.confirm("Delete this work?")) { await client.delete(`/admin/portfolio/${item.id}`); load(); setNotice("Work removed"); } }} title="Delete" data-testid={`delete-item-${item.id}`}><Trash2 size={16} /></button></div></div>) : <div className="empty-state"><span>—</span><p>Your work library is ready for its first piece.</p></div>}</div></main><footer className="admin-footer"><span data-testid="signed-in-user">Signed in as {user.email}</span><button onClick={logout} data-testid="logout-button"><LogOut size={15} /> Sign out</button></footer>{editing !== null && <PortfolioForm item={editing} close={() => setEditing(null)} saved={() => { setEditing(null); load(); setNotice("Work saved to the live portfolio"); }} />}</div>; }
function PortfolioForm({ item, close, saved }) { const [form, setForm] = useState({ category: item.category || "Social Media", media_type: item.media_type || "reel", title: item.title || "", label: item.label || "", media_url: item.media_url || "", media_data: item.media_data || "", mime_type: item.mime_type || "" }); const [error, setError] = useState(""); const update = e => setForm({ ...form, [e.target.name]: e.target.value }); const file = e => { const f = e.target.files[0]; if (!f) return; if (f.size > 30 * 1024 * 1024) return setError("Please choose a file under 30 MB."); const reader = new FileReader(); reader.onload = () => setForm(x => ({ ...x, media_data: reader.result, media_url: "", mime_type: f.type, media_type: f.type.startsWith("video") ? "reel" : "design" })); reader.readAsDataURL(f); }; const submit = async e => { e.preventDefault(); setError(""); try { if (!form.media_url && !form.media_data) throw new Error("Add a file or hosted media URL"); if (item.id) await client.put(`/admin/portfolio/${item.id}`, form); else await client.post("/admin/portfolio", form); saved(); } catch (err) { setError(err.response?.data?.detail || err.message); } }; return <div className="modal-backdrop"><form className="portfolio-form" onSubmit={submit} data-testid="portfolio-form"><button type="button" className="close-button" onClick={close} data-testid="close-portfolio-form"><X /></button><p className="kicker">{item.id ? "EDIT WORK" : "ADD NEW WORK"}</p><h2>{item.id ? "Refine this piece" : "Add to the library"}</h2><label>Niche / category<input name="category" value={form.category} onChange={update} required data-testid="portfolio-category-input" /></label><div className="form-split"><label>Type<select name="media_type" value={form.media_type} onChange={update} data-testid="portfolio-type-input"><option value="reel">Reel / video</option><option value="design">Design / image</option></select></label><label>Short label<input name="label" value={form.label} onChange={update} placeholder="e.g. Campaign 01" data-testid="portfolio-label-input" /></label></div><label>Title<input name="title" value={form.title} onChange={update} placeholder="Optional title" data-testid="portfolio-title-input" /></label><label>Upload file<input type="file" accept="image/*,video/*" onChange={file} data-testid="portfolio-file-input" /></label><div className="or-line"><span>or use a hosted URL</span></div><label>Media URL<input name="media_url" value={form.media_url} onChange={update} placeholder="https://..." data-testid="portfolio-url-input" /></label>{form.media_data && <p className="file-ready" data-testid="file-ready-indicator"><Check size={15} /> File ready to save</p>}{error && <p className="error-message" data-testid="portfolio-form-error">{error}</p>}<button className="primary-button" type="submit" data-testid="save-portfolio-button">Save to live portfolio <ArrowUpRight size={17} /></button></form></div>; }

export default function App() { return <BrowserRouter><Routes><Route path="/" element={<Home />} /><Route path="/login" element={<Login />} /><Route path="/admin" element={<Admin />} /></Routes></BrowserRouter>; }